
output: BubbleSort.o InsertionSort.o
	g++ BubbleSort.o InsertionSort.o -o output
	
BubbleSort.o: BubbleSort.c
	g++ -c BubbleSort.c 

InsertionSort.o: InsertionSort.c
	g++ -c InsertionSort.c

clean:

	rm *.o output
